# Generated by Django 4.2 on 2023-05-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaneData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('lane1_upper', models.FloatField()),
                ('lane1_lower', models.FloatField()),
                ('lane2_upper', models.FloatField()),
                ('lane2_lower', models.FloatField()),
            ],
        ),
    ]
