# Generated by Django 4.2 on 2023-05-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monotainers_stack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lanedata',
            name='lane',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lanedata',
            name='lower',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='lanedata',
            name='upper',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AlterUniqueTogether(
            name='lanedata',
            unique_together={('position', 'lane')},
        ),
        migrations.RemoveField(
            model_name='lanedata',
            name='lane1_lower',
        ),
        migrations.RemoveField(
            model_name='lanedata',
            name='lane1_upper',
        ),
        migrations.RemoveField(
            model_name='lanedata',
            name='lane2_lower',
        ),
        migrations.RemoveField(
            model_name='lanedata',
            name='lane2_upper',
        ),
    ]
