# Generated by Django 4.2 on 2023-05-03 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monotainers_stack', '0003_alter_lanedata_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lanedata',
            unique_together={('position', 'lane')},
        ),
    ]
