# Generated by Django 4.2 on 2023-05-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monotainers_stack', '0004_alter_lanedata_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_id', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Planogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_staged', models.IntegerField()),
                ('mapped', models.IntegerField()),
                ('missing', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Processed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_id', models.CharField(max_length=6)),
            ],
        ),
    ]
