# Generated by Django 4.2 on 2023-05-14 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monotainers_stack', '0005_pending_planogram_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='lane',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='monotainers_stack.planogram'),
        ),
        migrations.AddField(
            model_name='planogram',
            name='lane_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='planogram',
            name='lane_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planogram',
            name='trucks_ordered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planogram',
            name='trucks_required',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processed',
            name='lane',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='monotainers_stack.planogram'),
        ),
        migrations.AlterField(
            model_name='planogram',
            name='in_staged',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planogram',
            name='mapped',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planogram',
            name='missing',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planogram',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
